# Fine-tuning a model with the Trainer API

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [ ]:
# !pip install datasets evaluate transformers[sentencepiece]

Requirement already satisfied: datasets in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (4.8.4)
Requirement already satisfied: evaluate in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (0.4.6)
Requirement already satisfied: transformers[sentencepiece] in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (5.5.0)
Requirement already satisfied: filelock in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (2.4.4)
Requirement already satisfied: pyarrow>=21.0.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (2.33.1)
Requirement already satisfied: httpx<1.0.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (1.9.0)
Requirement already satisfied: packaging in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: regex>=2025.10.22 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from transformers[sentencepiece]) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from transformers[sentencepiece]) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from transformers[sentencepiece]) (0.7.0)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from transformers[sentencepiece]) (0.2.1)
Requirement already satisfied: protobuf in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from transformers[sentencepiece]) (7.34.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
from datasets import load_dataset
from transformers import AutoTokenizer, DataCollatorWithPadding

raw_datasets = load_dataset("glue", "mrpc")
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)


def tokenize_function(example):
    return tokenizer(example["sentence1"], example["sentence2"], truncation=True)


tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

/home/ollie/.cache/pypoetry/virtualenvs/llm-course-hugging-face-_giC5u1K-py3.14/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
from transformers import TrainingArguments

training_args = TrainingArguments("test-trainer")

/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory

In [4]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1166.11it/s]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [5]:
from transformers import Trainer

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
)

In [6]:
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.25it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.25it/s]

TrainOutput(global_step=1377, training_loss=0.3423558431166882, metrics={'train_runtime': 159.1771, 'train_samples_per_second': 69.131, 'train_steps_per_second': 8.651, 'total_flos': 405114969714960.0, 'train_loss': 0.3423558431166882, 'epoch': 3.0})

In [7]:
predictions = trainer.predict(tokenized_datasets["validation"])
print(predictions.predictions.shape, predictions.label_ids.shape)

(408, 2) (408,)

In [8]:
import numpy as np

preds = np.argmax(predictions.predictions, axis=-1)

In [10]:
import evaluate

metric = evaluate.load("glue", "mrpc")
metric.compute(predictions=preds, references=predictions.label_ids)

{'accuracy': 0.8431372549019608, 'f1': 0.8915254237288136}

In [12]:
def compute_metrics(eval_preds):
    metric = evaluate.load("glue", "mrpc")
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [14]:
# Old broken code
# training_args = TrainingArguments("test-trainer", evaluation_strategy="epoch")
training_args = TrainingArguments("test-trainer", eval_strategy="epoch")
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 17399.03it/s]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [15]:
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.18it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.30it/s]

TrainOutput(global_step=1377, training_loss=0.37609614508690487, metrics={'train_runtime': 167.9255, 'train_samples_per_second': 65.529, 'train_steps_per_second': 8.2, 'total_flos': 405114969714960.0, 'train_loss': 0.37609614508690487, 'epoch': 3.0})